#ifndef QT_HEADS_H
#define QT_HEADS_H
#include <QMutex>
#include <QObject>
#include <QDebug>
#include <QString>
#include <QStringList>
#include <QFrame>
#include <QWidget>
#include <QScreen>
#include <QMainWindow>
#include <QApplication>
#include <QMessageBox>
#include <QEvent>
#include <QFile>
#include <QCloseEvent>
#include <QList>
#include <QMap>
#include <QPainter>
#include <QPainterPath>
#include <QMutex>
#include <QImage>
#include <QPixmap>
#include <QBuffer>
#include <QPalette>
#include <QJsonObject>
#include <QJsonDocument>
#include <QJsonArray>
#include <QTimer>
#include <QAction>
#include <QMenu>
#include <QSystemTrayIcon>
#include <QGraphicsDropShadowEffect>
//#include <QOpenGLShaderProgram>
//#include <qopengl.h>
//#include <QOpenGLWidget>
#include <functional>
#include <QtConcurrent/QtConcurrent>
#include <QFuture>
#include <QEventLoop>
#include <QMessageBox>
#endif // QT_HEADS_H
